name: Test_Suit
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: build environment
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/test:stackVM-1.0 .
          docker push ${{ secrets.DOCKER_USERNAME }}/test:stackVM-1.0 .
