name: Test_Suit
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: build environment
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: docker build -t stack-vm:1.0 .
