name: Test_Suit
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: build environment
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: test
        env:
          DOCKER_PWD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t bilalmahmood19/test:stackVM-1.0 .
          echo ${DOCKER_PWD} | docker login -u bilalmahmood19 --password-stdin
          docker push bilalmahmood19/test:stackVM-1.0
          docker logout
